# Default values for jenkins.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

## Overrides for generated resource names
# See templates/_helpers.tpl
# nameOverride:
# fullnameOverride:

Master:
  Name: jenkins-master
  Image: "jenkins/jenkins"
  ImageTag: "2.121.3"
  ImagePullPolicy: "Always"
# ImagePullSecret: jenkins
  Component: "jenkins-master"
  UseSecurity: true
  AdminUser: admin
  AdminPassword: jenkins
  Cpu: "200m"
  Memory: "2048Mi"
  HostName: jenkins2.cloudzcp.io	# CHANGE
  # For minikube, set this to NodePort, elsewhere use LoadBalancer
  # Use ClusterIP if your setup includes ingress controller
  ServiceType: ClusterIP
  JavaOpts: -Duser.timezone=Asia/Seoul
  InstallPlugins:
    - kubernetes:1.12.0
    - workflow-job:2.23
    - workflow-aggregator:2.5
    - credentials-binding:1.16
    - git:3.9.1
    - timestamper:1.8.10
    - pipeline-utility-steps:2.1.0
    - config-file-provider:2.18
    - mask-passwords:2.12.0
    - keycloak:2.2.0
    - blueocean:1.8.2
    - matrix-auth:2.3
  Tolerations:
  - key: "management"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
    PodAnnotations: {}
  Affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: beta.kubernetes.io/arch
            operator: In
            values:
            - "amd64"
          - key: role
            operator: In
            values:
            - "management"
  Ingress:
    Annotations:
    # ingress.bluemix.net/ALB-ID: private-cr9b51e2d31cef4589984913b350fa8ed8-alb1  # CHANGE
      ingress.bluemix.net/redirect-to-https: "True"
    TLS:
    - hosts:
      - jenkins2.cloudzcp.io  # CHANGE
      secretName: cloudzcp-io-cert

Persistence:
  Enabled: true
  ## A manually managed Persistent Volume and Claim
  ## Requires Persistence.Enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  ExistingClaim: zcp-jenkins

## Install Default RBAC roles and bindings
rbac:
  serviceAccountName: zcp-system-admin

