apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: harbor
    chart: harbor
    component: database
    heritage: Tiller
    release: zcp-registry
  name: zcp-registry-harbor-database
  namespace: zcp-system
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: harbor
      component: database
      release: zcp-registry
  serviceName: zcp-registry-harbor-database
  template:
    metadata:
      labels:
        app: harbor
        chart: harbor
        component: database
        heritage: Tiller
        release: zcp-registry
    spec:
      securityContext:
        fsGroup: 999
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
              - key: role
                operator: In
                values:
                - management
      containers:
      - envFrom:
        - secretRef:
            name: zcp-registry-harbor-database
        image: goharbor/harbor-db:v1.7.5
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /docker-healthcheck.sh
          failureThreshold: 3
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: database
        readinessProbe:
          exec:
            command:
            - /docker-healthcheck.sh
          failureThreshold: 3
          initialDelaySeconds: 1
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/postgresql
          name: database-data
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - rm
        - -Rf
        - /var/lib/postgresql/data/lost+found;
        - rm
        - -Rf
        - /var/lib/postgresql/data;
        - mkdir
        - data;
        image: goharbor/harbor-db:dev
        imagePullPolicy: IfNotPresent
        name: remove-lost-found
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/postgresql
          name: database-data
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: management
        operator: Equal
        value: "true"
      volumes:
      - name: database-data
        persistentVolumeClaim:
          claimName: zcp-registry-postgresql
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
