apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    #volume.beta.kubernetes.io/storage-class: ibmc-file-bronze
    volume.beta.kubernetes.io/storage-class: ibmc-block-bronze
  labels:
    billingType: "hourly"
  name: zcp-catalog-mongodb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  #storageClassName: ibmc-file-bronze
  storageClassName: ibmc-block-bronze
